/*
Copyright 2020 The RUIJIE Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	v1alpha1 "pgoperator/pkg/apis/cluster/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePatroniClusters implements PatroniClusterInterface
type FakePatroniClusters struct {
	Fake *FakeRccpV1alpha1
	ns   string
}

var patroniclustersResource = schema.GroupVersionResource{Group: "rccp.ruijie.com.cn", Version: "v1alpha1", Resource: "patroniclusters"}

var patroniclustersKind = schema.GroupVersionKind{Group: "rccp.ruijie.com.cn", Version: "v1alpha1", Kind: "PatroniCluster"}

// Get takes name of the patroniCluster, and returns the corresponding patroniCluster object, and an error if there is any.
func (c *FakePatroniClusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PatroniCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(patroniclustersResource, c.ns, name), &v1alpha1.PatroniCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PatroniCluster), err
}

// List takes label and field selectors, and returns the list of PatroniClusters that match those selectors.
func (c *FakePatroniClusters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PatroniClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(patroniclustersResource, patroniclustersKind, c.ns, opts), &v1alpha1.PatroniClusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PatroniClusterList{ListMeta: obj.(*v1alpha1.PatroniClusterList).ListMeta}
	for _, item := range obj.(*v1alpha1.PatroniClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested patroniClusters.
func (c *FakePatroniClusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(patroniclustersResource, c.ns, opts))

}

// Create takes the representation of a patroniCluster and creates it.  Returns the server's representation of the patroniCluster, and an error, if there is any.
func (c *FakePatroniClusters) Create(ctx context.Context, patroniCluster *v1alpha1.PatroniCluster, opts v1.CreateOptions) (result *v1alpha1.PatroniCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(patroniclustersResource, c.ns, patroniCluster), &v1alpha1.PatroniCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PatroniCluster), err
}

// Update takes the representation of a patroniCluster and updates it. Returns the server's representation of the patroniCluster, and an error, if there is any.
func (c *FakePatroniClusters) Update(ctx context.Context, patroniCluster *v1alpha1.PatroniCluster, opts v1.UpdateOptions) (result *v1alpha1.PatroniCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(patroniclustersResource, c.ns, patroniCluster), &v1alpha1.PatroniCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PatroniCluster), err
}

// Delete takes name of the patroniCluster and deletes it. Returns an error if one occurs.
func (c *FakePatroniClusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(patroniclustersResource, c.ns, name, opts), &v1alpha1.PatroniCluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePatroniClusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(patroniclustersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PatroniClusterList{})
	return err
}

// Patch applies the patch and returns the patched patroniCluster.
func (c *FakePatroniClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PatroniCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(patroniclustersResource, c.ns, name, pt, data, subresources...), &v1alpha1.PatroniCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PatroniCluster), err
}
