/*
Copyright 2020 The RUIJIE Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	clusterv1alpha1 "pgoperator/pkg/apis/cluster/v1alpha1"
	versioned "pgoperator/pkg/client/clientset/versioned"
	internalinterfaces "pgoperator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "pgoperator/pkg/client/listers/cluster/v1alpha1"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PatroniClusterInformer provides access to a shared informer and lister for
// PatroniClusters.
type PatroniClusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PatroniClusterLister
}

type patroniClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPatroniClusterInformer constructs a new informer for PatroniCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPatroniClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPatroniClusterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPatroniClusterInformer constructs a new informer for PatroniCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPatroniClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RccpV1alpha1().PatroniClusters(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RccpV1alpha1().PatroniClusters(namespace).Watch(context.TODO(), options)
			},
		},
		&clusterv1alpha1.PatroniCluster{},
		resyncPeriod,
		indexers,
	)
}

func (f *patroniClusterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPatroniClusterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *patroniClusterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&clusterv1alpha1.PatroniCluster{}, f.defaultInformer)
}

func (f *patroniClusterInformer) Lister() v1alpha1.PatroniClusterLister {
	return v1alpha1.NewPatroniClusterLister(f.Informer().GetIndexer())
}
